{% set version = "0.25.0" %}

package:
  name: pyodide-build
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyodide-build/pyodide-build-{{ version }}.tar.gz
  sha256: 060abf97429a592788393fb9710f4c63b1ff45d14c248f0c710913efe4e70623
  patches:
    # this _should_ fail if the version of cmake changes below
    - 0000-no-cmake-from-pip.patch

build:
  noarch: python
  entry_points:
    - pyodide-build = pyodide_build.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - auditwheel-emscripten >=0.0.9,<0.1.0
    - cmake >=3.24
    - cython <3.0
    - loky
    - packaging
    - pydantic >=1.10.2,<2
    - pyodide-cli >=0.2.1,<0.3.0
    - python >=3.10
    - python-build >=1.0.0
    - pyodide-lock ==0.1.0a4
    - pyyaml
    - requests
    - resolvelib
    - rich
    - ruamel.yaml
    - tomli
    - typer
    - types-requests
    - unearth >=0.6,<1.0.0
    - virtualenv
    - wheel

test:
  files:
    - test_pyodide_cli.py
  imports:
    - pyodide_build
  requires:
    - pip
  commands:
    - pip check
    # TODO: deprecated, but maybe figure out all the env vars needed for this to actually run
    # - pyodide-build --help
    - which pyodide-build || where pyodide-build
    - pyodide build-recipes --help
    - pyodide skeleton --help
    - pyodide config --help

about:
  home: https://github.com/pyodide/pyodide
  summary: Tools for building Pyodide
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
