{% set version = "0.27.3" %}

package:
  name: pyodide-build
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyodide-build/pyodide_build-{{ version }}.tar.gz
  sha256: c9d6c5b233289862433e0e4e4e834a5f2a81bdfef0ff47ce8f48db3e9dde3ff0
  patches:
    # this _should_ fail if the version of cmake changes below
    - 0000-no-cmake-from-pip.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling
    - pip
    - python >=3.12
  run:
    - auditwheel-emscripten >=0.0.9,<0.1.0
    - cmake >=3.24
    - packaging
    - pydantic >=2,<3
    - pyodide-cli >=0.2.1,<0.3.dev0
    - python >=3.12
    - python-build >=1.2.0,<1.3.dev0
    - pyodide-lock ==0.1.0a6
    - pyyaml
    - requests
    - resolvelib
    - rich
    - ruamel.yaml
    - typer
    - unearth >=0.6,<1.dev0
    - virtualenv
    - wheel

test:
  imports:
    - pyodide_build
  requires:
    - pip
  commands:
    - pip check
    - pyodide build-recipes --help
    - pyodide skeleton --help
    - pyodide config --help

about:
  home: https://github.com/pyodide/pyodide-build
  summary: Tools for building Pyodide
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
